dustinfarris/ember-django-adapter

docs/contributing.md

Running the adapter locally is a bit awkward.  Here's how I do it.

Add instructions for local development

---

CHANGELOG.md
addon/serializers/drf.js
docs/pagination.md
mkdocs.yml
tests/dummy/app/models/paginated-post.js
tests/integration/crud-success-test.js
tests/integration/pagination-test.js
tests/unit/serializers/drf-test.js

This PR is taking over from #38 because it's not possible edit the destination branch. The PR was originally against the version-1.0 branch which has now been merged into master.

Pagination

---

addon/adapters/drf.js
app/adapters/application.js
config/environment.js
docs/configuring.md
docs/index.md
mkdocs.yml
tests/unit/adapters/drf-test.js

This PR adds a new option to remove trailing slashes from API URLs.
Example usage:
```js
// in your app's config/environment.js
var ENV = {
APP: {
API_ADD_TRAILING_SLASHES: false
...
}
};
```

Add option to remove trailing slashes

---

CHANGELOG.md
README.md
app/adapters/application.js
app/adapters/drf.js
app/serializers/application.js
app/serializers/drf.js
blueprints/.jshintrc
blueprints/drf-adapter/files/app/adapters/__name__.js
blueprints/drf-adapter/index.js
blueprints/drf-serializer/files/app/serializers/__name__.js
blueprints/drf-serializer/index.js
docs/embedded-records.md
docs/extending.md
docs/usage.md
mkdocs.yml

This creates blueprints that allow the user to extend the adapter/serializer, and adds documentation explaining how to use these blueprints when working with embedded records.

Working with embedded records

---

CHANGELOG.md
addon/adapters/drf.js
tests/integration/crud-failure-test.js
tests/unit/adapters/drf-test.js

Return jqXHR for non-400 errors.

---

config/environment.js
docs/configuring.md

This adds a more reasonable default for `API_HOST`.  The existing empty string would just point the adapter at Ember's express server, which makes no sense in DRF world.
Should fix #4.

Change default `API_HOST`

---

addon/adapters/drf.js
app/adapters/drf.js
docs/configuring.md
docs/trailing-slashes.md
mkdocs.yml
tests/unit/adapters/drf-test.js

The trailing slashes config isn't really something that changes between environments, so it shouldn't be configured as such.
This PR redefines how addTrailingSlashes is configured.
This is a breaking change.

Move trailing slashes config

---

mkdocs.yml

This is good to go, but it won't actually work until https://github.com/tomchristie/mkdocs/pull/338 is merged.

Add Google Analytics to docs

---

README.md

Going to leave this open to comment for a few days.
/cc @benkonrath @holandes22

Revised Goals

---

addon/adapters/drf.js
docs/coalesce-find-requests.md
mkdocs.yml
tests/unit/adapters/drf-test.js

This adds documentation that describes how to write a simple filter in DRF to support coalesced requests.  Additionally, we override `_stripIDFromURL` so that it can handle trailing slashes.
The [original `_stripIDFromURL`](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js#L594-L610) implementation seems overly complicated, so I chose to simplify it down to a simple proxy to buildURL call with the record type.
Thanks to @g-cassie for inspiration on the DRF filter.
Fixes #32

Add support for coalesceFindRequests

---

addon/serializers/drf.js

Hello! I'm using ED 1.0.0 beta 15 and getting a deprecation warning. Apparently they change the name of `store.metaForType` to `store.setMetadataFor`. This pull request fix the problem.
I hope this help!

rename deprecated method name to fit ED 1.0.0.beta15

---

config/ember-try.js
docs/contributing.md
package.json

Playing with [ember-try](https://www.npmjs.com/package/ember-try).  This lays the groundwork for eventually supporting a dependency matrix.  For now, I think we should just support the latest ED beta until 1.0 lands.  At that point we'll want to be careful about breaking changes for >=1.0.
You can invoke ember try with:
```
ember try:testall
```
which runs all scenarios in `config/ember-try.js` (latest ember data beta and ember data canary).  You can run a specific scenario by giving its name, e.g.:
```
ember try ember-data-canary
```
(side note: we have 2 failing tests on canary)

Add `ember try` scenarios

---

addon/adapters/drf.js
tests/unit/adapters/drf-test.js

Using `snapshot.constructor.typeKey` is deprecated on latest `ember-data`.
`snapshot.typeKey` reference: http://emberjs.com/api/data/classes/DS.Snapshot.html#property_typeKey

Use `snapshot.typeKey` on adapter's _stripIDFromUrl

---

addon/adapters/drf.js
tests/acceptance/crud-success-test.js

This allows for other types of find queries to be handled correctly,
e.g. `store.find('person', {name: 'Ben'});`.
Added an acceptance test for this, but it turns out that 2 pagination tests were failing because of changes to the handling of find queries. This patch fixes those, too, so all tests are now passing in canary.
[Ember-data now uses a new buildURL signature](https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/ember-data/lib/adapters/build-url-mixin.js#L51)
Sorry for the delay on this!

Add requestType to buildURL.

---

addon/adapters/drf.js
addon/serializers/drf.js
bower.json
package.json
tests/unit/adapters/drf-test.js
tests/unit/serializers/drf-test.js

Hey, it's me again. Newest beta introduced some more changes to reference the type for a `Snapshot`/`Model`.
`typeKey` and `constructor.typeKey` are now deprecated and both use the `modelName` property instead.
Updated the usage of those attributes, their respective tests, and both node and bower dependencies to point at the latest beta.
Let me know in any case!

Updated for ember-data@1.0.0-beta.18

---

docs/pagination.md

Documentation for integrating with Ember CLI Pagination addon

Ember CLI Pagination integration

---

docs/hyperlinked-related-fields.md

I was a little too ambitious with the documentation about paginated nested URLs. While the API does work fine, it doesn't work with EDA so it shouldn't be included. It might be possible to get it working but until it works, it should be removed.

Remove documentation about paginated nested URLs.

---

README.md
addon/adapters/drf.js
bower.json
config/ember-try.js
docs/non-field-errors.md
docs/pagination.md
package.json
tests/acceptance/crud-failure-test.js
tests/acceptance/crud-success-test.js
tests/acceptance/pagination-test.js
tests/acceptance/relationship-links-test.js
tests/acceptance/relationships-test.js
tests/unit/adapters/drf-test.js

@dustinfarris @benkonrath I tested this in a project of mine and it that work ok for me, but if would be great if you guys can test it in your projects before merge.
Something I doesn't quite like is how I handle the non_field_errors case where I need to stick the key in the meta field as there is no sensible place to put it in a Jsonapi error object.
- Not tested with older ED versions as we won't support beta versions
- Ember 1.12.1 or later is needed from now on
Closes #103

Updating adapter to support ember-data 1.13.5

---

tests/acceptance/crud-success-test.js

Updated test from troubleshooting for #115.
Explicitly set an id and ensure that the id is in the POST payload when .save() is called.

Update create record test in crud-success-test.js

---

bower.json
config/ember-try.js
package.json
tests/acceptance/embedded-records-test.js
tests/dummy/app/models/embedded-comments-post.js
tests/dummy/app/models/embedded-post-comment.js
tests/dummy/app/serializers/embedded-comments-post.js
tests/dummy/app/serializers/embedded-post-comment.js

This avoids having to manually test the embedded records feature as we update to new ED versions. This test passes on master but fails with #114 which what I expect. 
I also updated the ember-try config to test with E 1.13 / ED 1.13 and E 1.12 / ED 1.13. These are the versions we have listed as supported so it makes sense to test against them.

Add acceptance test for embedded records.

---

tests/acceptance/embedded-records-test.js
tests/dummy/app/models/embedded-comments-post.js
tests/dummy/app/models/embedded-post-comment.js
tests/dummy/app/serializers/embedded-post-comment.js

Ids for embedded beolongsTo aren't being sent when creating a record. My interpretation is that setting `post: {serialize: 'id', deserialize: 'records'}` in the serializer should allow the embedded record to work on retrieve but also allow the id to be set on create / update. The test shows that ED is sending `null` instead of the id.
I've included a couple of other cleanups / fixes in the PR. The `belongsTo create` is the relevant test. Any thoughts here?

Add a test for embedded belongsTo create with id.

---

CHANGELOG.md
README.md
addon/serializers/drf.js
bower.json
config/ember-try.js
docs/coalesce-find-requests.md
docs/hyperlinked-related-fields.md
docs/non-field-errors.md
docs/pagination.md
package.json
tests/acceptance/crud-failure-test.js
tests/acceptance/crud-success-test.js
tests/acceptance/embedded-records-test.js
tests/acceptance/pagination-test.js
tests/acceptance/relationship-links-test.js
tests/acceptance/relationships-test.js
tests/unit/serializers/drf-test.js

I still need to update the documentation.
There is one remaining deprecation warning but it is an application level warning so I don't think we should override this function in EDA.
```
DEPRECATION: The default behavior of shouldReloadAll will change in Ember Data 2.0 to always return false when there is at least one "post" record in the store. If you would like to preserve the current behavior please override shouldReloadAll in your adapter:application and return true.
```
closes #110
closes #111

Update to ember 1.13 serializer api.

---

README.md
addon/adapters/drf.js
bower.json
config/ember-try.js
docs/index.md
docs/non-field-errors.md
package.json
tests/acceptance/crud-failure-test.js
tests/unit/adapters/drf-test.js

Went ahead and worked on fixing #113 based on the previous discussion.

Update non_field_errors object to follow spec

---

README.md
addon/serializers/drf.js
bower.json
config/ember-try.js
package.json
tests/.jshintrc
tests/acceptance/crud-success-test.js
tests/acceptance/pagination-test.js
tests/dummy/app/templates/application.hbs
tests/unit/serializers/drf-test.js

This is ready to go. ~~except that I would like to get confirmation that this in fact fixes #132.~~
**Edit**: Let's deal with #132 separately.
Fixes #128 
Fixes #130

Switch back to rest serializer

---

addon/serializers/drf.js
tests/acceptance/pagination-test.js

This happens on page 2 when the previous link without the page=1 query param indicates a url for page 1. I'm hitting this with `djangorestframework==3.2.4`. The test has been updated to match the output from DRF.

Support DRF not adding page query param for the previous link.

---

addon/adapters/drf.js

This allows for nested DRF model error messages, such as:
```
{
"billing_email":["Oppgi en gyldig e-postadresse"],
"account":
{"email":["Oppgi en gyldig e-postadresse"]}
}
```
This allows for serializers like this:
```python
class CustomerSerializer(serializers.ModelSerializer):
account = UserSerializer(read_only=False)
class UserSerializer(serializers.ModelSerializer):
class Meta:
model = User
fields = ('...')
```

Allow nested errors for nested models, fixes #131

---

addon/adapters/drf.js
tests/acceptance/crud-failure-test.js

I changed the implementation to what @marius0 suggested—I think it is cleaner.  Also added a test.
An important caveat is that JSON API—and Ember Data by extension—does not support nested resources and therefore does not support nested errors.  What we are doing here is essentially allowing the nested errors to come through as parent resource errors with slash-delimited attribute names.  This allows the response to be processed without blowing up, but technically the result is incorrect—the nested resource's `isValid` continues to be true.  There is not much we can do about it except to put on this band-aid.
Related discussion: https://github.com/json-api/json-api/issues/899
See also #131 and #137 
/cc @marius0 @peec

Update nested error handling

---

addon/serializers/drf.js
docs/pagination.md
tests/unit/serializers/drf-test.js

I removed the requirement to have a ```count``` attribute in the DRF list response.
This closes #136

Do not require count attribute in response

---

docs/coalesce-find-requests.md

Disable pagination in example of Coalesce filter, see #144

Coalesce Filter  update docs regarding pagination.

---

addon/adapters/drf.js
tests/unit/adapters/drf-test.js

Including strings in payloads causes maximum call stack size exceeded error because of the recursive nature of `_drfToJsonAPIValidationErrors`.
This PR converts:
```
{
key: 'value'
}
```
into:
```
{
key: ['value']
}
```
for each recursion of `_drfToJsonAPIValidationErrors`.

Map payload strings to arrays

---

.jshintrc
addon/serializers/drf.js

- Since 2.5 Ember.merge raises a deprecation. This PR fixes that and makes sure the addon would still work with versions Ember that still don't implement `assign` and in browser environments that have `Object.assign`. 
- Fix `.jshintrc` deprecated opts.

clean Ember.merge deprecation and fix jshintrc

---

docs/coalesce-find-requests.md

Avoid "NotImplementedError: `request.QUERY_PARAMS` has been deprecated in favor of `request.query_params` since version 3.0, and has been fully removed as of version 3.2." when c&p'ing `CoalesceFilterBackend`.

update coalesce-find-requests code sample to django-rest-framework >=3.0

---

addon/adapters/drf.js
config/ember-try.js
package.json

ember-django-adapter currently imports `AdapterError` and `InvalidError` from `ember-data/-private`, but this isn't necessary and breaks in the latest version of ember data (3.11.0).
While I was at it, I also made ember-data a peer dependency as suggested in https://github.com/dustinfarris/ember-django-adapter/issues/219.

Import adapter errors from "standard" location & make ember-data a peer dependency.
